// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// To enable, install dependencies and uncomment the defineConfig below.
// See: https://www.prisma.io/docs/orm/prisma-schema/overview
